import type { Metadata } from "next";
import { Source_Sans_3, Crimson_Pro } from 'next/font/google';
import "./globals.css";

const sans = Source_Sans_3({ subsets: ['latin'], variable: '--font-sans' });
const serif = Crimson_Pro({ subsets: ['latin'], variable: '--font-serif' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${serif.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
